### ISSUE TITLE
Feature idea: Badges

### ISSUE THREAD

**Issue by NetOperatorWibby** [GoodForPoC/GoodForPoC#12]
Or, stamps of approval.

I'm planning a site for Boston area businesses and thought of having a GoodForPoc badge on applicable business pages. No idea what they should look like but I do like those code coverage badges, seen on npm repos.

@GoodForPoC/owners @GoodForPoC/moderators

**Comment by jalcine** [comment]
Hey! Just letting you know that this is still an idea in progress.

**Comment by jalcine** [comment]
@NetOperatorWibby you have thoughts on how this should look?

**Comment by NetOperatorWibby** [comment]
@jalcine Nope, not yet. I'll come up with some sketches and share later.
