### ISSUE TITLE
Strip + Rotate PII for GoodForPoc

### ISSUE THREAD

**Issue by jalcine** [GoodForPoC/GoodForPoC#2]
So we've open-sourced the static site impl of http://goodforpocin.tech! There's a few more things we ought to do before moving forward with contributions.

- [x] Drop google*.html file
- [x] Move to DNS confirmation of Site Verification [link][1].

[1]: https://www.google.com/webmasters/verification/verification

**Comment by cattsmall** [comment]
DONE
