### ISSUE TITLE
Icon Standards

### ISSUE THREAD

**Issue by adekunleoduye** [GoodForPoC/GoodForPoC#46]
## Feature idea 

Standardize how we use icons and create ones that reflect the GoodForPoC brand.

**Specific steps to take:**

- [x] Figure out how we want to handle icons (SVG, icon fonts, etc.)
- [x] Identify what icons we need 
- [x] Create icons/locate icon font

**Comment by cattsmall** [comment]
We could make this easy on ourselves and use an open source icon font. [How about this one?](https://material.io/icons/) It has some good faces:

![image](https://user-images.githubusercontent.com/2164037/34465345-0ec07496-ee76-11e7-8d42-cf4d9e1a3d11.png)

**Comment by adekunleoduye** [comment]
Oh yeah, that sounds like a good to me. Less for us to do!

What are people's thoughts on either self hosting (my perfer method) or using a Google web fonts url for these icons?


On Dec 31, 2017 22:00, Catt Small <notifications@github.com> wrote:

We could make this easy on ourselves and use an open source icon font. How about this one?<https://material.io/icons/> It has some good faces:

[image]<https://user-images.githubusercontent.com/2164037/34465345-0ec07496-ee76-11e7-8d42-cf4d9e1a3d11.png>

**Comment by cattsmall** [comment]
Okay, I made a PR including the self-hosted icon font ✨
