### ISSUE TITLE
Build testing platform

### ISSUE THREAD

**Issue by cattsmall** [GoodForPoC/GoodForPoC#5]
We strongly believe in test-driven development and would like help implementing testing as part of our development process.

**Comment by jalcine** [comment]
Word. Tests are dope!

Ember practically has all of its testing there out of the box. What kind of test cases should we kick this off with?

I was thinking the following:
 - [ ] navigation link check // makes sure we don't remove anything by accident.
 - [ ] links to jump to log in page, log out page // may need to leave broken
 - [ ] testing a contact us page layout

**Comment by jalcine** [comment]
Got a few of these up and running, largely around data retrieval from the API.

**Comment by cattsmall** [comment]
@jalcine im late to this but this all sounds good to me. can we close this?

**Comment by jalcine** [comment]
We can!
